TOPOJSON = node_modules/.bin/topojson

all: \
	topojson/ABW/0.json \
	topojson/AFG/0.json \
	topojson/AFG/1.json \
	topojson/AFG/2.json \
	topojson/AGO/0.json \
	topojson/AGO/1.json \
	topojson/AGO/2.json \
	topojson/AGO/3.json \
	topojson/AIA/0.json \
	topojson/ALA/0.json \
	topojson/ALA/1.json \
	topojson/ALB/0.json \
	topojson/ALB/1.json \
	topojson/ALB/2.json \
	topojson/ALB/3.json \
	topojson/AND/0.json \
	topojson/AND/1.json \
	topojson/ARE/0.json \
	topojson/ARE/1.json \
	topojson/ARG/0.json \
	topojson/ARG/1.json \
	topojson/ARG/2.json \
	topojson/ARM/0.json \
	topojson/ARM/1.json \
	topojson/ASM/0.json \
	topojson/ASM/1.json \
	topojson/ASM/2.json \
	topojson/ASM/3.json \
	topojson/ATA/0.json \
	topojson/ATF/0.json \
	topojson/ATF/1.json \
	topojson/ATG/0.json \
	topojson/ATG/1.json \
	topojson/AUS/0.json \
	topojson/AUS/1.json \
	topojson/AUS/2.json \
	topojson/AUT/0.json \
	topojson/AUT/1.json \
	topojson/AUT/2.json \
	topojson/AZE/0.json \
	topojson/AZE/1.json \
	topojson/BDI/0.json \
	topojson/BDI/1.json \
	topojson/BDI/2.json \
	topojson/BDI/3.json \
	topojson/BDI/4.json \
	topojson/BEL/0.json \
	topojson/BEL/1.json \
	topojson/BEL/2.json \
	topojson/BEL/3.json \
	topojson/BEL/4.json \
	topojson/BEN/0.json \
	topojson/BEN/1.json \
	topojson/BEN/2.json \
	topojson/BES/0.json \
	topojson/BFA/0.json \
	topojson/BFA/1.json \
	topojson/BFA/2.json \
	topojson/BGD/0.json \
	topojson/BGD/1.json \
	topojson/BGD/2.json \
	topojson/BGD/3.json \
	topojson/BGD/4.json \
	topojson/BGR/0.json \
	topojson/BGR/1.json \
	topojson/BGR/2.json \
	topojson/BHR/0.json \
	topojson/BHR/1.json \
	topojson/BHS/0.json \
	topojson/BHS/1.json \
	topojson/BIH/0.json \
	topojson/BIH/1.json \
	topojson/BIH/2.json \
	topojson/BIH/3.json \
	topojson/BLM/0.json \
	topojson/BLR/0.json \
	topojson/BLR/1.json \
	topojson/BLR/2.json \
	topojson/BLZ/0.json \
	topojson/BLZ/1.json \
	topojson/BMU/0.json \
	topojson/BMU/1.json \
	topojson/BOL/0.json \
	topojson/BOL/1.json \
	topojson/BOL/2.json \
	topojson/BOL/3.json \
	topojson/BRA/0.json \
	topojson/BRA/1.json \
	topojson/BRA/2.json \
	topojson/BRA/3.json \
	topojson/BRB/0.json \
	topojson/BRB/1.json \
	topojson/BRN/0.json \
	topojson/BRN/1.json \
	topojson/BRN/2.json \
	topojson/BTN/0.json \
	topojson/BTN/1.json \
	topojson/BTN/2.json \
	topojson/BVT/0.json \
	topojson/BWA/0.json \
	topojson/BWA/1.json \
	topojson/BWA/2.json \
	topojson/CA-/0.json \
	topojson/CAF/0.json \
	topojson/CAF/1.json \
	topojson/CAF/2.json \
	topojson/CAN/0.json \
	topojson/CAN/1.json \
	topojson/CAN/2.json \
	topojson/CAN/3.json \
	topojson/CCK/0.json \
	topojson/CHE/0.json \
	topojson/CHE/1.json \
	topojson/CHE/2.json \
	topojson/CHE/3.json \
	topojson/CHL/0.json \
	topojson/CHL/1.json \
	topojson/CHL/2.json \
	topojson/CHL/3.json \
	topojson/CHN/0.json \
	topojson/CHN/1.json \
	topojson/CHN/2.json \
	topojson/CHN/3.json \
	topojson/CIV/0.json \
	topojson/CIV/1.json \
	topojson/CIV/2.json \
	topojson/CIV/3.json \
	topojson/CL-/0.json \
	topojson/CMR/0.json \
	topojson/CMR/1.json \
	topojson/CMR/2.json \
	topojson/COD/0.json \
	topojson/COD/1.json \
	topojson/COD/2.json \
	topojson/COD/3.json \
	topojson/COG/0.json \
	topojson/COG/1.json \
	topojson/COG/2.json \
	topojson/COK/0.json \
	topojson/COL/0.json \
	topojson/COL/1.json \
	topojson/COL/2.json \
	topojson/COM/0.json \
	topojson/COM/1.json \
	topojson/CPV/0.json \
	topojson/CPV/1.json \
	topojson/CRI/0.json \
	topojson/CRI/1.json \
	topojson/CRI/2.json \
	topojson/CUB/0.json \
	topojson/CUB/1.json \
	topojson/CUB/2.json \
	topojson/CUW/0.json \
	topojson/CXR/0.json \
	topojson/CYM/0.json \
	topojson/CYM/1.json \
	topojson/CYP/0.json \
	topojson/CYP/1.json \
	topojson/CZE/0.json \
	topojson/CZE/1.json \
	topojson/CZE/2.json \
	topojson/DEU/0.json \
	topojson/DEU/1.json \
	topojson/DEU/2.json \
	topojson/DEU/3.json \
	topojson/DJI/0.json \
	topojson/DJI/1.json \
	topojson/DJI/2.json \
	topojson/DMA/0.json \
	topojson/DMA/1.json \
	topojson/DNK/0.json \
	topojson/DNK/1.json \
	topojson/DNK/2.json \
	topojson/DOM/0.json \
	topojson/DOM/1.json \
	topojson/DOM/2.json \
	topojson/DZA/0.json \
	topojson/DZA/1.json \
	topojson/DZA/2.json \
	topojson/ECU/0.json \
	topojson/ECU/1.json \
	topojson/ECU/2.json \
	topojson/ECU/3.json \
	topojson/EGY/0.json \
	topojson/EGY/1.json \
	topojson/ERI/0.json \
	topojson/ERI/1.json \
	topojson/ERI/2.json \
	topojson/ESH/0.json \
	topojson/ESH/1.json \
	topojson/ESP/0.json \
	topojson/ESP/1.json \
	topojson/ESP/2.json \
	topojson/ESP/3.json \
	topojson/ESP/4.json \
	topojson/EST/0.json \
	topojson/EST/1.json \
	topojson/EST/2.json \
	topojson/EST/3.json \
	topojson/ETH/0.json \
	topojson/ETH/1.json \
	topojson/ETH/2.json \
	topojson/ETH/3.json \
	topojson/FIN/0.json \
	topojson/FIN/1.json \
	topojson/FIN/2.json \
	topojson/FIN/3.json \
	topojson/FIN/4.json \
	topojson/FJI/0.json \
	topojson/FJI/1.json \
	topojson/FJI/2.json \
	topojson/FLK/0.json \
	topojson/FRA/0.json \
	topojson/FRA/1.json \
	topojson/FRA/2.json \
	topojson/FRA/3.json \
	topojson/FRA/4.json \
	topojson/FRA/5.json \
	topojson/FRO/0.json \
	topojson/FRO/1.json \
	topojson/FRO/2.json \
	topojson/FSM/0.json \
	topojson/FSM/1.json \
	topojson/GAB/0.json \
	topojson/GAB/1.json \
	topojson/GAB/2.json \
	topojson/GBR/0.json \
	topojson/GBR/1.json \
	topojson/GBR/2.json \
	topojson/GEO/0.json \
	topojson/GEO/1.json \
	topojson/GEO/2.json \
	topojson/GGY/0.json \
	topojson/GHA/0.json \
	topojson/GHA/1.json \
	topojson/GHA/2.json \
	topojson/GIB/0.json \
	topojson/GIN/0.json \
	topojson/GIN/1.json \
	topojson/GIN/2.json \
	topojson/GIN/3.json \
	topojson/GLP/0.json \
	topojson/GLP/1.json \
	topojson/GLP/2.json \
	topojson/GMB/0.json \
	topojson/GMB/1.json \
	topojson/GMB/2.json \
	topojson/GNB/0.json \
	topojson/GNB/1.json \
	topojson/GNB/2.json \
	topojson/GNQ/0.json \
	topojson/GNQ/1.json \
	topojson/GRC/0.json \
	topojson/GRC/1.json \
	topojson/GRC/2.json \
	topojson/GRD/0.json \
	topojson/GRD/1.json \
	topojson/GRL/0.json \
	topojson/GRL/1.json \
	topojson/GRL/2.json \
	topojson/GTM/0.json \
	topojson/GTM/1.json \
	topojson/GTM/2.json \
	topojson/GUF/0.json \
	topojson/GUF/1.json \
	topojson/GUF/2.json \
	topojson/GUM/0.json \
	topojson/GUM/1.json \
	topojson/GUY/0.json \
	topojson/GUY/1.json \
	topojson/GUY/2.json \
	topojson/HKG/0.json \
	topojson/HKG/1.json \
	topojson/HMD/0.json \
	topojson/HND/0.json \
	topojson/HND/1.json \
	topojson/HND/2.json \
	topojson/HRV/0.json \
	topojson/HRV/1.json \
	topojson/HRV/2.json \
	topojson/HTI/0.json \
	topojson/HTI/1.json \
	topojson/HTI/2.json \
	topojson/HTI/3.json \
	topojson/HUN/0.json \
	topojson/HUN/1.json \
	topojson/HUN/2.json \
	topojson/IDN/0.json \
	topojson/IDN/1.json \
	topojson/IDN/2.json \
	topojson/IMN/0.json \
	topojson/IND/0.json \
	topojson/IND/1.json \
	topojson/IND/2.json \
	topojson/IND/3.json \
	topojson/IOT/0.json \
	topojson/IRL/0.json \
	topojson/IRL/1.json \
	topojson/IRN/0.json \
	topojson/IRN/1.json \
	topojson/IRN/2.json \
	topojson/IRQ/0.json \
	topojson/IRQ/1.json \
	topojson/IRQ/2.json \
	topojson/ISL/0.json \
	topojson/ISL/1.json \
	topojson/ISL/2.json \
	topojson/ISR/0.json \
	topojson/ISR/1.json \
	topojson/ITA/0.json \
	topojson/ITA/1.json \
	topojson/ITA/2.json \
	topojson/ITA/3.json \
	topojson/JAM/0.json \
	topojson/JAM/1.json \
	topojson/JEY/0.json \
	topojson/JOR/0.json \
	topojson/JOR/1.json \
	topojson/JOR/2.json \
	topojson/JPN/0.json \
	topojson/JPN/1.json \
	topojson/JPN/2.json \
	topojson/KAZ/0.json \
	topojson/KAZ/1.json \
	topojson/KAZ/2.json \
	topojson/KEN/0.json \
	topojson/KEN/1.json \
	topojson/KEN/2.json \
	topojson/KEN/3.json \
	topojson/KEN/4.json \
	topojson/KEN/5.json \
	topojson/KGZ/0.json \
	topojson/KGZ/1.json \
	topojson/KHM/0.json \
	topojson/KHM/1.json \
	topojson/KHM/2.json \
	topojson/KHM/3.json \
	topojson/KHM/4.json \
	topojson/KIR/0.json \
	topojson/KNA/0.json \
	topojson/KNA/1.json \
	topojson/KO-/0.json \
	topojson/KO-/1.json \
	topojson/KO-/2.json \
	topojson/KOR/0.json \
	topojson/KOR/1.json \
	topojson/KOR/2.json \
	topojson/KWT/0.json \
	topojson/KWT/1.json \
	topojson/LAO/0.json \
	topojson/LAO/1.json \
	topojson/LAO/2.json \
	topojson/LBN/0.json \
	topojson/LBN/1.json \
	topojson/LBN/2.json \
	topojson/LBR/0.json \
	topojson/LBR/1.json \
	topojson/LBR/2.json \
	topojson/LBR/3.json \
	topojson/LBY/0.json \
	topojson/LBY/1.json \
	topojson/LCA/0.json \
	topojson/LCA/1.json \
	topojson/LIE/0.json \
	topojson/LIE/1.json \
	topojson/LKA/0.json \
	topojson/LKA/1.json \
	topojson/LKA/2.json \
	topojson/LSO/0.json \
	topojson/LSO/1.json \
	topojson/LTU/0.json \
	topojson/LTU/1.json \
	topojson/LTU/2.json \
	topojson/LUX/0.json \
	topojson/LUX/1.json \
	topojson/LUX/2.json \
	topojson/LUX/3.json \
	topojson/LUX/4.json \
	topojson/LVA/0.json \
	topojson/LVA/1.json \
	topojson/LVA/2.json \
	topojson/MAC/0.json \
	topojson/MAF/0.json \
	topojson/MAR/0.json \
	topojson/MAR/1.json \
	topojson/MAR/2.json \
	topojson/MAR/3.json \
	topojson/MAR/4.json \
	topojson/MCO/0.json \
	topojson/MDA/0.json \
	topojson/MDA/1.json \
	topojson/MDG/0.json \
	topojson/MDG/1.json \
	topojson/MDG/2.json \
	topojson/MDG/3.json \
	topojson/MDG/4.json \
	topojson/MDV/0.json \
	topojson/MEX/0.json \
	topojson/MEX/1.json \
	topojson/MEX/2.json \
	topojson/MHL/0.json \
	topojson/MKD/0.json \
	topojson/MKD/1.json \
	topojson/MKD/2.json \
	topojson/MLI/0.json \
	topojson/MLI/1.json \
	topojson/MLI/2.json \
	topojson/MLI/3.json \
	topojson/MLI/4.json \
	topojson/MLT/0.json \
	topojson/MMR/0.json \
	topojson/MMR/1.json \
	topojson/MMR/2.json \
	topojson/MMR/3.json \
	topojson/MNE/0.json \
	topojson/MNE/1.json \
	topojson/MNG/0.json \
	topojson/MNG/1.json \
	topojson/MNG/2.json \
	topojson/MNP/0.json \
	topojson/MNP/1.json \
	topojson/MOZ/0.json \
	topojson/MOZ/1.json \
	topojson/MOZ/2.json \
	topojson/MOZ/3.json \
	topojson/MRT/0.json \
	topojson/MRT/1.json \
	topojson/MRT/2.json \
	topojson/MSR/0.json \
	topojson/MTQ/0.json \
	topojson/MTQ/1.json \
	topojson/MTQ/2.json \
	topojson/MUS/0.json \
	topojson/MUS/1.json \
	topojson/MWI/0.json \
	topojson/MWI/1.json \
	topojson/MWI/2.json \
	topojson/MWI/3.json \
	topojson/MYS/0.json \
	topojson/MYS/1.json \
	topojson/MYS/2.json \
	topojson/MYT/0.json \
	topojson/MYT/1.json \
	topojson/NAM/0.json \
	topojson/NAM/1.json \
	topojson/NAM/2.json \
	topojson/NCL/0.json \
	topojson/NCL/1.json \
	topojson/NCL/2.json \
	topojson/NER/0.json \
	topojson/NER/1.json \
	topojson/NER/2.json \
	topojson/NER/3.json \
	topojson/NFK/0.json \
	topojson/NGA/0.json \
	topojson/NGA/1.json \
	topojson/NGA/2.json \
	topojson/NIC/0.json \
	topojson/NIC/1.json \
	topojson/NIC/2.json \
	topojson/NIU/0.json \
	topojson/NLD/0.json \
	topojson/NLD/1.json \
	topojson/NLD/2.json \
	topojson/NLD/3.json \
	topojson/NOR/0.json \
	topojson/NOR/1.json \
	topojson/NOR/2.json \
	topojson/NPL/0.json \
	topojson/NPL/1.json \
	topojson/NPL/2.json \
	topojson/NPL/3.json \
	topojson/NPL/4.json \
	topojson/NRU/0.json \
	topojson/NRU/1.json \
	topojson/NZL/0.json \
	topojson/NZL/1.json \
	topojson/NZL/2.json \
	topojson/NZL/3.json \
	topojson/OMN/0.json \
	topojson/OMN/1.json \
	topojson/OMN/2.json \
	topojson/PAK/0.json \
	topojson/PAK/1.json \
	topojson/PAK/2.json \
	topojson/PAK/3.json \
	topojson/PAN/0.json \
	topojson/PAN/1.json \
	topojson/PAN/2.json \
	topojson/PAN/3.json \
	topojson/PCN/0.json \
	topojson/PER/0.json \
	topojson/PER/1.json \
	topojson/PER/2.json \
	topojson/PER/3.json \
	topojson/PHL/0.json \
	topojson/PHL/1.json \
	topojson/PHL/2.json \
	topojson/PHL/3.json \
	topojson/PLW/0.json \
	topojson/PLW/1.json \
	topojson/PNG/0.json \
	topojson/PNG/1.json \
	topojson/PNG/2.json \
	topojson/POL/0.json \
	topojson/POL/1.json \
	topojson/POL/2.json \
	topojson/PRI/0.json \
	topojson/PRI/1.json \
	topojson/PRK/0.json \
	topojson/PRK/1.json \
	topojson/PRK/2.json \
	topojson/PRT/0.json \
	topojson/PRT/1.json \
	topojson/PRT/2.json \
	topojson/PRT/3.json \
	topojson/PRY/0.json \
	topojson/PRY/1.json \
	topojson/PRY/2.json \
	topojson/PSE/0.json \
	topojson/PSE/1.json \
	topojson/PSE/2.json \
	topojson/PYF/0.json \
	topojson/QAT/0.json \
	topojson/QAT/1.json \
	topojson/REU/0.json \
	topojson/REU/1.json \
	topojson/REU/2.json \
	topojson/ROU/0.json \
	topojson/ROU/1.json \
	topojson/RUS/0.json \
	topojson/RUS/1.json \
	topojson/RUS/2.json \
	topojson/RUS/3.json \
	topojson/RWA/0.json \
	topojson/RWA/1.json \
	topojson/RWA/2.json \
	topojson/SAU/0.json \
	topojson/SAU/1.json \
	topojson/SDN/0.json \
	topojson/SDN/1.json \
	topojson/SDN/2.json \
	topojson/SDN/3.json \
	topojson/SDN/4.json \
	topojson/SEN/0.json \
	topojson/SEN/1.json \
	topojson/SEN/2.json \
	topojson/SEN/3.json \
	topojson/SEN/4.json \
	topojson/SGP/0.json \
	topojson/SGS/0.json \
	topojson/SHN/0.json \
	topojson/SHN/1.json \
	topojson/SJM/0.json \
	topojson/SJM/1.json \
	topojson/SLB/0.json \
	topojson/SLB/1.json \
	topojson/SLE/0.json \
	topojson/SLE/1.json \
	topojson/SLE/2.json \
	topojson/SLE/3.json \
	topojson/SLV/0.json \
	topojson/SLV/1.json \
	topojson/SLV/2.json \
	topojson/SMR/0.json \
	topojson/SMR/1.json \
	topojson/SMX/0.json \
	topojson/SOM/0.json \
	topojson/SOM/1.json \
	topojson/SOM/2.json \
	topojson/SP-/0.json \
	topojson/SPM/0.json \
	topojson/SPM/1.json \
	topojson/SRB/0.json \
	topojson/SRB/1.json \
	topojson/SRB/2.json \
	topojson/SSD/0.json \
	topojson/SSD/1.json \
	topojson/SSD/2.json \
	topojson/SSD/3.json \
	topojson/SSD/4.json \
	topojson/STP/0.json \
	topojson/STP/1.json \
	topojson/SUR/0.json \
	topojson/SUR/1.json \
	topojson/SUR/2.json \
	topojson/SVK/0.json \
	topojson/SVK/1.json \
	topojson/SVK/2.json \
	topojson/SVN/0.json \
	topojson/SVN/1.json \
	topojson/SVN/2.json \
	topojson/SWE/0.json \
	topojson/SWE/1.json \
	topojson/SWE/2.json \
	topojson/SWZ/0.json \
	topojson/SWZ/1.json \
	topojson/SYC/0.json \
	topojson/SYR/0.json \
	topojson/SYR/1.json \
	topojson/SYR/2.json \
	topojson/TCA/0.json \
	topojson/TCA/1.json \
	topojson/TCD/0.json \
	topojson/TCD/1.json \
	topojson/TCD/2.json \
	topojson/TCD/3.json \
	topojson/TGO/0.json \
	topojson/TGO/1.json \
	topojson/TGO/2.json \
	topojson/THA/0.json \
	topojson/THA/1.json \
	topojson/THA/2.json \
	topojson/THA/3.json \
	topojson/TJK/0.json \
	topojson/TJK/1.json \
	topojson/TJK/2.json \
	topojson/TJK/3.json \
	topojson/TKL/0.json \
	topojson/TKL/1.json \
	topojson/TKM/0.json \
	topojson/TKM/1.json \
	topojson/TLS/0.json \
	topojson/TLS/1.json \
	topojson/TLS/2.json \
	topojson/TON/0.json \
	topojson/TON/1.json \
	topojson/TTO/0.json \
	topojson/TTO/1.json \
	topojson/TUN/0.json \
	topojson/TUN/1.json \
	topojson/TUN/2.json \
	topojson/TUR/0.json \
	topojson/TUR/1.json \
	topojson/TUR/2.json \
	topojson/TUV/0.json \
	topojson/TUV/1.json \
	topojson/TWN/0.json \
	topojson/TWN/1.json \
	topojson/TWN/2.json \
	topojson/TZA/0.json \
	topojson/TZA/1.json \
	topojson/TZA/2.json \
	topojson/TZA/3.json \
	topojson/UGA/0.json \
	topojson/UGA/1.json \
	topojson/UGA/2.json \
	topojson/UGA/3.json \
	topojson/UGA/4.json \
	topojson/UKR/0.json \
	topojson/UKR/1.json \
	topojson/UKR/2.json \
	topojson/UMI/0.json \
	topojson/UMI/1.json \
	topojson/URY/0.json \
	topojson/URY/1.json \
	topojson/URY/2.json \
	topojson/USA/0.json \
	topojson/USA/1.json \
	topojson/USA/2.json \
	topojson/UZB/0.json \
	topojson/UZB/1.json \
	topojson/UZB/2.json \
	topojson/VAT/0.json \
	topojson/VCT/0.json \
	topojson/VCT/1.json \
	topojson/VEN/0.json \
	topojson/VEN/1.json \
	topojson/VEN/2.json \
	topojson/VGB/0.json \
	topojson/VIR/0.json \
	topojson/VIR/1.json \
	topojson/VNM/0.json \
	topojson/VNM/1.json \
	topojson/VNM/2.json \
	topojson/VNM/3.json \
	topojson/VNM/4.json \
	topojson/VUT/0.json \
	topojson/VUT/1.json \
	topojson/WLF/0.json \
	topojson/WLF/1.json \
	topojson/WLF/2.json \
	topojson/WSM/0.json \
	topojson/WSM/1.json \
	topojson/WSM/2.json \
	topojson/YEM/0.json \
	topojson/YEM/1.json \
	topojson/YEM/2.json \
	topojson/ZAF/0.json \
	topojson/ZAF/1.json \
	topojson/ZAF/2.json \
	topojson/ZMB/0.json \
	topojson/ZMB/1.json \
	topojson/ZMB/2.json \
	topojson/ZWE/0.json \
	topojson/ZWE/1.json \
	topojson/ZWE/2.json \

.SECONDARY:

zip/%.zip:
	mkdir -p $(dir $@)
	curl "http://data.biogeo.ucdavis.edu/data/gadm2/shp/$*_adm.zip" -o $@.download
	mv $@.download $@

shp/%: zip/%.zip
	mkdir -p $@
	unzip -d $@ $<
	touch $@

# topojson/PRK/0.json
topojson/%.json: shp/$(dir %)
	mkdir -p $(dir $@)
	$(TOPOJSON) -o $@ -p -- shp/$(dir $*)$(patsubst %/,%,$(dir $*))_adm$(notdir $*).shp

clean:
	rm -rf topojson/*